# Hiukassuodin ja -siloitin sisätilapaikannuksessa

## Teknologian kuvaus

Here is an equation.

\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 

You may refer to using `\@ref(eq:binom)`, like see Equation \@ref(eq:binom).

## Koeasetelma

Labeled theorems can be referenced in text using `\@ref(thm:tri)`, for example, check out this smart theorem \@ref(thm:tri).

::: {.theorem #tri}
For a right triangle, if $c$ denotes the *length* of the hypotenuse
and $a$ and $b$ denote the lengths of the **other** two sides, we have
$$a^2 + b^2 = c^2$$
:::

Read more here <https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html>.

## AoA-menetelmistä

### MUSIC-algoritmi

Footnotes are put inside the square brackets after a caret `^[]`. Like this one ^[This is a footnote.]. 

Citations. Reference items in your bibliography file(s) using `@key`.

For example, we are using the **bookdown** package [@R-bookdown] (check out the last code chunk in index.Rmd to see how this citation key was added) in this sample book, which was built on top of R Markdown and **knitr** [@xie2015] (this citation was added manually in an external file book.bib). 
Note that the `.bib` files need to be listed in the index.Rmd with the YAML `bibliography` key.

The RStudio Visual Markdown Editor can also make it easier to insert citations: <https://rstudio.github.io/visual-markdown-editing/#/citations>

## Datan kuvaus

## Ongelman ja mallien kuvaus

### Datan valinta

Convex hull goes here.

### Uskottavuusmallit

### Dynaaminen malli

## Algoritmien toteutuksesta

## Karttasovitusalgoritmi

## Reitinhakualgoritmi

## Parametrien valinnasta

## Tulokset
