# Lopuksi

Tässä tutkielmassa on esitetty pääpiirteittäin hiukkassuodin- ja hiukkassiloitinalgoritmien teoria Bayesilaisessa tilastotieteellisessä viitekehyksessä. Tutkielmassa on lisäksi käyty läpi uudelleenotantaa efektiivisen otoskoon perusteella hyödyntävä SIR-suodinalgoritmi sekä käsitelty algoritmin varianssin estimointia. Tutkielmassa on myös esitetty SIR-algoritmin parametrien valintaan, suorituskykyyn sekä konvergenssiin liittyviä tuloksia.

Tutkielmassa on lisäksi esitetty WB-sisätilapaikannusalgoritmi, joka toteuttaa SIR-algoritmin, estimoi jakaumaestimaatin varianssin ja hyödyntää sisätilapaikannuksen karttasovitusalgoritmia. Tutkielmassa on lopuksi tarkasteltu miten eri suunnitteluparametrien valinnat vaikuttavat algoritmin suorituskykyyn kattavan, todelliseen ongelmaan ja dataan perustuvan paikannuskokeen avulla.

Algoritmia ja järjestelmää voitaisiin mahdollisesti edelleen parantaa esimerkiksi käyttämällä tagia, jonka kiihtyvyysmittarin tuottama data olisi AT-2-tagia luotettavampaa. Kiihtyvyyssataa voitaisiin hyödyntää esimerkiksi informatiivisen liikemallin luomisessa. 

Koe-esimerkin perusteella tutkielmassa käsitelty ALVar-varianssi estimoi hyvin jakaumaestimaatin varianssia. ALVar-varianssiestimaattia voitaisiin edelleen hyödyntää esimerkiksi adaptiivisen viipeen siloittimen toteuttamisessa. Vastaavasti KALMAN-SUODIN.

Varianssiestimaattia olisi mahdollista hyödyntää WB-sisätilapaikannusalgoritmin dynaamisen mallin kohinaparametrin $q$ säätämisessä niin, että kohinaa lisättäisiin tai vähennettäisiin varianssiestimaatin perusteella. Tämä voitaisiin toteuttaa esimerkiksi käyttämällä lähtökohtaisesti pienempää $q$-arvoa ja lisäämällä siihen keskihajonnan estimaatti, jota on painotettu suunnitteluparametrilla $\alpha$, ts. ennen dynaamisen mallin sovitusta päivtettäisiin kohinaparametri $q_k = q_k+\alpha\sqrt{\hat{\sigma}^2_{k-1}}$.

Varianssiestimaattia voisi hyödyntää myös hiukkasten lukumäärän $N$ adaptiivisessa valinnassa niin, että matala varianssi vähentää estimoinnissa käytettävien hiukkasten määrää. Tällaista varianssiin perustuvaa hiukkasmäärän muuttamista ehdottavat muun muassa Lee ja Whiteley (2018) [@Lee-2018]. Hiukkasten määrään muuttamista  XXX Vastaavasti voisi parantaa myös arvioimalla konvergenssia esimerkiksi ***. 

Algoritmin suorituskykyä voitaisiin mahdollisesti myös parantaa käyttämällä RSSI-kynnysarvon sijaan tai ohella esimerkiksi menetelmää, jossa datasta poistettaisiin kullakin aika-askeleella ne kulmahavainnot, jotka poikkeavat kulmahavaintojen suuntakonsensuksesta. Jättämällä osa havainnoista uskottavuusfunktioiden ulkopuolelle nopeuttaisi algoritmin laskentaa, mutta saattaisi parantaa myös algoritmin tarkkuutta.

Liitteenä olevia polkuja tarkastelemalla puolestaan huomataan, että nyt toteutetun algoritmin sijantiestimaatilla on taipumus jäädä osassa testiympäristöä jälkeen itse tagin sijainnista. Tätä ongelmaa voitaisiin mahdollisesti lieventää käyttämällä mm. Yi Chenging &al. artikkelissa "Improved Particle Filter Algorithm for Multi-Target Detection and Tracking" (2024) [@Cheng-2024] esittämää menetelmää, jossa partikkelit jaetaan ns. seurantahiukkasiin sekä etsintähiukkasiin, joista ainoastaan edellisiä käytetään sijaintiestimaatin luomisessa ja jälkimmäisten annetaan liikkua suuremmilla kohina-arvoilla. Näin mahdollistetaan satunnaiskulkumallilla laajempi signaaliavaruuden tutkinta ja nopeampi ongelmatilanteista toipuminen ilman, että sijaintiestimaatit kärsivät liikemalliin lisätystä kohinasta.

Ongelma voitaisiin ratkaista myös käyttämällä ekskluusiopolygonien ohella ns. pehmeitä rajoitteita (kts. esim. TODO), jolloin ekskluusiopolygonien ympärille luotaisiin rajoitevyöhyke, jolle osuvat hiukkaset saisivat rangaistuksen riippuen siitä, kuinka lähellä itse ekskluusiopolygonin reunaa ne ovat. Rangaistusarvon luomisessa voitaisiin käyttää esimerkiksi eksponentiaalista tai kvadraattista hajoamista.

Kokeen tuloksia voisi puolestaan myös Vastaavasti parametrien vaikutusta voisi tarkastella sensitiivisyysanalyysin avulla.