---
urlcolor: blue   
linkcolor: blue
citecolor: blue
toccolor: blue
output:
  pdf_document:
    toc: true
    number_sections: true
    toc_depth: 4
citation_package: natbib
lang: fi
documentclass: book
bibliography: [book.bib, packages.bib]
fontsize: 12pt
classoption: a4paper, twoside
link-citations: yes
github-repo: rintakumpu/progradu
site: bookdown::bookdown_site
---

\setlength\parindent{24pt}
\setlength\parskip{3pt}

```{r setup, include=FALSE, cache=FALSE}
#Knitr options
knitr::opts_chunk$set(echo = FALSE, fig.width=3, fig.height=2.8, fig.show='hold', fig.align='center', warning = FALSE, cache = TRUE, cache.path = 'output/cache/', fig.path = 'output/figures/')

# Used libraries
library(knitr) # For creating PDF
library(pander)
library(bookdown)

# Automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'pander'
), 'packages.bib')
```

# Johdanto

Lorem ipsum.

## Notaatioista

Lorem ipsum.

## Suodin- ja siloitteluongelmat

Lorem ipsum.

## Suodin- ja siloitteluongelmien historiaa

Lorem ipsum.

<!--chapter:end:index.Rmd-->

# Monte Carlo -menetelmist채

## Monte Carlo -menetelmien historiaa

## Monte Carlo -approksimaatio

## T채rkeytysotanta

## Sekventiaalinen Monte Carlo




<!--chapter:end:01-mc_menetelmista.Rmd-->


# Bayesilainen suodin ja siloitin

Placeholder


## Bayesilainen suodin
## Bayesilainen siloitin
## Kalman-suotimen ja hiukassuotimen eroista

<!--chapter:end:02-bayes_suodin_siloitin.Rmd-->


# Hiukkassuotimet

Placeholder


## Saapasremmisuodin
## SIR-algoritmi
### Interpolaatiosta
### Parametrien valinta
### Marginaalijakauma
### Aikakompleksisuus
### Konvergenssituloksia
## Varianssin estimointi

<!--chapter:end:03-hiukassuotimet.Rmd-->

# Hiukkasiloittimet

Add an appendix as a special kind of un-numbered part: `# (APPENDIX) Other stuff {-}` (followed by `# A chapter`). Chapters in an appendix are prepended with letters instead of numbers.

## Offline-algoritmit

Lorem ipsum

### SIR-siloitin

## Online-algoritmit

Lorem ipsum

<!--chapter:end:04-hiukassiloittimet.Rmd-->


# Hiukassuodin ja -siloitin sis채tilapaikannuksessa

Placeholder


## Teknologian kuvaus
## Koeasetelma
## AoA-menetelmist채
### MUSIC-algoritmi
## Datan kuvaus
## Ongelman ja mallien kuvaus
### Datan valinta
### Uskottavuusmallit
### Dynaaminen malli
## Algoritmien toteutuksesta
## Karttasovitusalgoritmi
## Reitinhakualgoritmi
## Parametrien valinnasta
## Tulokset

<!--chapter:end:05-paikannusesimerkki.Rmd-->

# Lopuksi

Lorem ipsum


<!--chapter:end:06-lopuksi.Rmd-->

`r if (knitr::is_html_output()) '
# Kirjallisuutta {-}
'`

<!--chapter:end:07-lahteet.Rmd-->

